service: my-service
provider:
  name: aws
  runtime: nodejs14.x
  region: us-east-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - ses:SendEmail
      Resource: "*"
functions:
  sendEmail:
    handler: handler.sendEmail
events:
  - http:
      path: send-email
      method: post
      cors: true
